# Generated by Django 5.2.4 on 2025-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_invitation_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.FloatField(null=True),
        ),
    ]
