# Generated by Django 5.2.4 on 2025-07-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_score_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
